name: CI

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
    - master
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
     - name: checkout project
       uses: actions/checkout@v2
     
     - name: setup node version
       uses: actions/setup-node@v1
       with:
         node-version: '12'
       
     - name: Resolve dependencies
       run: npm ci
       
     - name: running tests
       run: npm test -- --coverage
       env:
         ci: true
         
     - name: upload test coverage
       uses: actions/upload-artifact@v2
       with:
        name: code-coverage
        path: coverage
         
     - name: build project
       if: github.event_name == 'push'
       run: npm run build

     - name: upload build
       uses: actions/upload-artifact@v2
       with:
        name: build
        path: build

     - name: deploy to staging
       if: github.event_name == 'push'
       run: npx surge --project ./build --domain 201720200@acad.unijuazeiro.edu.br
       env: 
         SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
         SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
