name: CI

on: 
  pull_request:
    branch: [master]

jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
     - name: show projects files
       run: ls -la
     - name: checkout project
       uses: action/checkout@2
     - name: show projects files
       run: ls -la
